---
- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k3s
    - k3s-node

- name: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount k3s filesystems
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
  loop_control:
    loop_var: mounted_fs

- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-node.service"
    - /etc/rancher/k3s
    - /var/lib/kubelet
    - /var/lib/rancher/k3s

- name: Stop docker containers
  shell: 'docker stop $(docker ps -a -q --filter "name=k8s_") | xargs docker rm'
  become: yes
  ignore_errors: yes

- name: Remove CNI namespaces
  shell: 'ip netns show 2>/dev/null | grep cni- | xargs -r -t -n 1 ip netns delete'
  become: yes
  tags: cni

- name: Delete network interface(s) that match 'master cni0'
  shell: |
          ip link show 2>/dev/null | grep "master cni0" | while read ignore iface ignore;
          do
            iface=${iface%%@*}
            [ -z "$iface" ] || ip link delete $iface
          done
  tags: network
  become: yes

- name: Delete 'cni0' and 'flannel.1' interfaces
  shell: "ip link delete {{ item }}"
  with_items:
    - cni0
    - flannel.1
  become: yes
  tags: network

- name: daemon_reload
  systemd:
    daemon_reload: yes
