---

all:
  children:
    master:
      hosts:
        amd-server.hftex:
      vars:
        ansible_user: centos
        #ansible_connection: local
        ansible_ssh_private_key_file: ~/.ssh/office.rsa
        extra_server_args: '--docker --disable traefik'

    gateway_node:
      hosts:
        zprime-09:
      vars:
        extra_agent_args: '--docker --node-label "prime-server=box" --node-taint "has-nvdimm=true:NoSchedule"'
    
    matching_engine_node:
      hosts:
        zprime-10:
      vars:
        extra_agent_args: '--docker'

    node:
      children:
        gateway_node:
        matching_engine_node:
      vars:
        ansible_user: prime
        ansible_ssh_private_key_file: ~/.ssh/office.rsa

    k3s_cluster:
      children:
        master:
        node:

...
