---

all:
  children:
    master:
      hosts:
        zprime-09.hftex:
      vars:
        ansible_user: prime
        ansible_ssh_private_key_file: ~/.ssh/office.rsa
        extra_server_args: '--docker --disable traefik'

    node_01:
      hosts:
        demo02.staging:
      vars:
        ansible_user: prime
        # mock for taints
        extra_agent_args: '--docker --node-label "prime-server=box" --node-taint "has-nvdimm=true:NoSchedule"'

    node_02:
      hosts:
        zprime-09.hftex:
      vars:
        ansible_user: prime
        extra_agent_args: '--docker'

    node:
      children:
        node_01:
        node_02:
      vars:
        ansible_ssh_private_key_file: ~/.ssh/office.rsa

    k3s_cluster:
      children:
        master:
        node:

...
